/**
 * Team & league name normalization.
 * Different sources spell teams differently (e.g. "FC Barcelona" vs "Barcelona"
 * vs "Barça"). We normalize to a canonical form so matches can be deduped.
 */

const TEAM_ALIASES: Record<string, string> = {
  // Premier League
  "man city": "Manchester City",
  "manchester city": "Manchester City",
  "manchester city fc": "Manchester City",
  "man utd": "Manchester United",
  "man united": "Manchester United",
  "manchester united": "Manchester United",
  "manchester united fc": "Manchester United",
  "newcastle": "Newcastle United",
  "newcastle utd": "Newcastle United",
  "tottenham": "Tottenham Hotspur",
  "spurs": "Tottenham Hotspur",
  "tottenham hotspur": "Tottenham Hotspur",
  "wolves": "Wolverhampton Wanderers",
  "wolverhampton": "Wolverhampton Wanderers",
  "brighton": "Brighton & Hove Albion",
  "brighton hove albion": "Brighton & Hove Albion",
  "west ham": "West Ham United",
  "west ham united": "West Ham United",
  "leicester": "Leicester City",
  "leicester city": "Leicester City",
  "aston villa": "Aston Villa",
  "crystal palace": "Crystal Palace",
  "nottingham forest": "Nottingham Forest",
  "nottm forest": "Nottingham Forest",
  "afc bournemouth": "Bournemouth",
  "bournemouth": "Bournemouth",
  "fulham": "Fulham",
  "brentford": "Brentford",
  "everton": "Everton",
  "liverpool": "Liverpool",
  "arsenal": "Arsenal",
  "chelsea": "Chelsea",
  "leeds": "Leeds United",
  "leeds united": "Leeds United",
  "burnley": "Burnley",
  "luton": "Luton Town",
  "luton town": "Luton Town",
  "sheffield utd": "Sheffield United",
  "sheffield united": "Sheffield United",
  "ipswich": "Ipswich Town",
  "ipswich town": "Ipswich Town",
  "southampton": "Southampton",
  // La Liga
  "real madrid": "Real Madrid",
  "barcelona": "FC Barcelona",
  "fc barcelona": "FC Barcelona",
  "barca": "FC Barcelona",
  "atletico madrid": "Atletico Madrid",
  "atletico": "Atletico Madrid",
  "athletico madrid": "Atletico Madrid",
  "athletic bilbao": "Athletic Bilbao",
  "athletic club": "Athletic Bilbao",
  "real sociedad": "Real Sociedad",
  "villarreal": "Villarreal",
  "real betis": "Real Betis",
  "betis": "Real Betis",
  "sevilla": "Sevilla",
  "valencia": "Valencia",
  "celta vigo": "Celta Vigo",
  "celta": "Celta Vigo",
  "getafe": "Getafe",
  "osasuna": "Osasuna",
  "rayo vallecano": "Rayo Vallecano",
  "mallorca": "Mallorca",
  "alaves": "Alaves",
  "las palmas": "Las Palmas",
  "girona": "Girona",
  "girona fc": "Girona",
  "espanyol": "Espanyol",
  "leganes": "Leganes",
  "valladolid": "Valladolid",
  // Serie A
  "juventus": "Juventus",
  "inter": "Inter Milan",
  "inter milan": "Inter Milan",
  "internazionale": "Inter Milan",
  "ac milan": "AC Milan",
  "milan": "AC Milan",
  "roma": "AS Roma",
  "as roma": "AS Roma",
  "lazio": "Lazio",
  "napoli": "Napoli",
  "atalanta": "Atalanta",
  "fiorentina": "Fiorentina",
  "torino": "Torino",
  "bologna": "Bologna",
  "udinese": "Udinese",
  "sassuolo": "Sassuolo",
  "genoa": "Genoa",
  "monza": "Monza",
  "lecce": "Lecce",
  "verona": "Hellas Verona",
  "hellas verona": "Hellas Verona",
  "cagliari": "Cagliari",
  "empoli": "Empoli",
  "frosinone": "Frosinone",
  "salernitana": "Salernitana",
  "como": "Como",
  "parma": "Parma",
  "venezia": "Venezia",
  // Bundesliga
  "bayern munich": "Bayern Munich",
  "bayern": "Bayern Munich",
  "borussia dortmund": "Borussia Dortmund",
  "dortmund": "Borussia Dortmund",
  "bvb": "Borussia Dortmund",
  "rb leipzig": "RB Leipzig",
  "leipzig": "RB Leipzig",
  "leverkusen": "Bayer Leverkusen",
  "bayer leverkusen": "Bayer Leverkusen",
  "frankfurt": "Eintracht Frankfurt",
  "eintracht frankfurt": "Eintracht Frankfurt",
  "wolfsburg": "Wolfsburg",
  "mainz": "Mainz 05",
  "mainz 05": "Mainz 05",
  "freiburg": "Freiburg",
  "hoffenheim": "Hoffenheim",
  "tsg hoffenheim": "Hoffenheim",
  "augsburg": "Augsburg",
  "werder bremen": "Werder Bremen",
  "bremen": "Werder Bremen",
  "stuttgart": "VfB Stuttgart",
  "vfb stuttgart": "VfB Stuttgart",
  "bochum": "VfL Bochum",
  "vfl bochum": "VfL Bochum",
  "union berlin": "Union Berlin",
  "hertha": "Hertha Berlin",
  "hertha berlin": "Hertha Berlin",
  "schalke": "Schalke 04",
  "schalke 04": "Schalke 04",
  "hamburg": "Hamburger SV",
  "hamburger sv": "Hamburger SV",
  "st pauli": "St. Pauli",
  "st. pauli": "St. Pauli",
  "holstein kiel": "Holstein Kiel",
  // Ligue 1
  "psg": "Paris Saint-Germain",
  "paris saint-germain": "Paris Saint-Germain",
  "paris saint germain": "Paris Saint-Germain",
  "paris sg": "Paris Saint-Germain",
  "marseille": "Marseille",
  "olympique marseille": "Marseille",
  "monaco": "AS Monaco",
  "as monaco": "AS Monaco",
  "lyon": "Lyon",
  "olympique lyonnais": "Lyon",
  "lille": "Lille",
  "lille osc": "Lille",
  "nice": "Nice",
  "ogc nice": "Nice",
  "rennes": "Rennes",
  "stade rennais": "Rennes",
  "lens": "Lens",
  "rc lens": "Lens",
  "nantes": "Nantes",
  "fc nantes": "Nantes",
  "strasbourg": "Strasbourg",
  "rc strasbourg": "Strasbourg",
  "montpellier": "Montpellier",
  "toulouse": "Toulouse",
  "fc toulouse": "Toulouse",
  "brest": "Brest",
  "stade brestois": "Brest",
  "reims": "Reims",
  "stade de reims": "Reims",
  "le havre": "Le Havre",
  "auxerre": "Auxerre",
  "angers": "Angers",
  "saint-etienne": "Saint-Etienne",
  "saint etienne": "Saint-Etienne",
  // Champions League / Europa teams handled by above
};

const LEAGUE_ALIASES: Record<string, { name: string; country: string }> = {
  "eng premier league": { name: "Premier League", country: "England" },
  "premier league": { name: "Premier League", country: "England" },
  "epl": { name: "Premier League", country: "England" },
  "barclays premier league": { name: "Premier League", country: "England" },
  "english premier league": { name: "Premier League", country: "England" },
  "championship": { name: "Championship", country: "England" },
  "efl championship": { name: "Championship", country: "England" },
  "league one": { name: "League One", country: "England" },
  "league two": { name: "League Two", country: "England" },
  "fa cup": { name: "FA Cup", country: "England" },
  "efl cup": { name: "EFL Cup", country: "England" },
  "carabao cup": { name: "EFL Cup", country: "England" },
  "spa la liga": { name: "La Liga", country: "Spain" },
  "la liga": { name: "La Liga", country: "Spain" },
  "laliga": { name: "La Liga", country: "Spain" },
  "primera division": { name: "La Liga", country: "Spain" },
  "spanish la liga": { name: "La Liga", country: "Spain" },
  "copa del rey": { name: "Copa del Rey", country: "Spain" },
  "ita serie a": { name: "Serie A", country: "Italy" },
  "serie a": { name: "Serie A", country: "Italy" },
  "italian serie a": { name: "Serie A", country: "Italy" },
  "coppa italia": { name: "Coppa Italia", country: "Italy" },
  "ger bundesliga": { name: "Bundesliga", country: "Germany" },
  "bundesliga": { name: "Bundesliga", country: "Germany" },
  "german bundesliga": { name: "Bundesliga", country: "Germany" },
  "2. bundesliga": { name: "2. Bundesliga", country: "Germany" },
  "dfb pokal": { name: "DFB Pokal", country: "Germany" },
  "fra ligue 1": { name: "Ligue 1", country: "France" },
  "ligue 1": { name: "Ligue 1", country: "France" },
  "french ligue 1": { name: "Ligue 1", country: "France" },
  "ligue 2": { name: "Ligue 2", country: "France" },
  "coupe de france": { name: "Coupe de France", country: "France" },
  "ned eredivisie": { name: "Eredivisie", country: "Netherlands" },
  "eredivisie": { name: "Eredivisie", country: "Netherlands" },
  "por primeira liga": { name: "Primeira Liga", country: "Portugal" },
  "primeira liga": { name: "Primeira Liga", country: "Portugal" },
  "liga portugal": { name: "Primeira Liga", country: "Portugal" },
  "sco premiership": { name: "Scottish Premiership", country: "Scotland" },
  "scottish premiership": { name: "Scottish Premiership", country: "Scotland" },
  "spl": { name: "Scottish Premiership", country: "Scotland" },
  "bel first div a": { name: "First Division A", country: "Belgium" },
  "jupiler pro league": { name: "First Division A", country: "Belgium" },
  "belgian pro league": { name: "First Division A", country: "Belgium" },
  "tur super lig": { name: "Süper Lig", country: "Turkey" },
  "super lig": { name: "Süper Lig", country: "Turkey" },
  "turkish super lig": { name: "Süper Lig", country: "Turkey" },
  "gre super league": { name: "Super League Greece", country: "Greece" },
  "super league greece": { name: "Super League Greece", country: "Greece" },
  "swi super league": { name: "Swiss Super League", country: "Switzerland" },
  "swiss super league": { name: "Swiss Super League", country: "Switzerland" },
  "aus bundesliga": { name: "Austrian Bundesliga", country: "Austria" },
  "austrian bundesliga": { name: "Austrian Bundesliga", country: "Austria" },
  "den superliga": { name: "Danish Superliga", country: "Denmark" },
  "danish superliga": { name: "Danish Superliga", country: "Denmark" },
  "swe allsvenskan": { name: "Allsvenskan", country: "Sweden" },
  "allsvenskan": { name: "Allsvenskan", country: "Sweden" },
  "nor eliteserien": { name: "Eliteserien", country: "Norway" },
  "eliteserien": { name: "Eliteserien", country: "Norway" },
  "fin veikkausliiga": { name: "Veikkausliiga", country: "Finland" },
  "veikkausliiga": { name: "Veikkausliiga", country: "Finland" },
  "pol ekstraklasa": { name: "Ekstraklasa", country: "Poland" },
  "ekstraklasa": { name: "Ekstraklasa", country: "Poland" },
  "cze first league": { name: "Czech First League", country: "Czech Republic" },
  "mls": { name: "MLS", country: "USA" },
  "major league soccer": { name: "MLS", country: "USA" },
  "bra serie a": { name: "Brasileirão", country: "Brazil" },
  "serie a brasil": { name: "Brasileirão", country: "Brazil" },
  "brasileirao": { name: "Brasileirão", country: "Brazil" },
  "arg primera division": { name: "Primera División", country: "Argentina" },
  "liga profesional": { name: "Primera División", country: "Argentina" },
  "mex liga mx": { name: "Liga MX", country: "Mexico" },
  "liga mx": { name: "Liga MX", country: "Mexico" },
  "jpn j1 league": { name: "J1 League", country: "Japan" },
  "j1 league": { name: "J1 League", country: "Japan" },
  "kor k league 1": { name: "K League 1", country: "South Korea" },
  "k league 1": { name: "K League 1", country: "South Korea" },
  "chn super league": { name: "Chinese Super League", country: "China" },
  "chinese super league": { name: "Chinese Super League", country: "China" },
  "saudi pro league": { name: "Saudi Pro League", country: "Saudi Arabia" },
  "saudi professional league": { name: "Saudi Pro League", country: "Saudi Arabia" },
  "uefa champions league": { name: "Champions League", country: "Europe" },
  "champions league": { name: "Champions League", country: "Europe" },
  "ucl": { name: "Champions League", country: "Europe" },
  "uefa europa league": { name: "Europa League", country: "Europe" },
  "europa league": { name: "Europa League", country: "Europe" },
  "uel": { name: "Europa League", country: "Europe" },
  "uefa europa conference league": { name: "Conference League", country: "Europe" },
  "conference league": { name: "Conference League", country: "Europe" },
  "uecl": { name: "Conference League", country: "Europe" },
  "uefa nations league": { name: "UEFA Nations League", country: "Europe" },
  "nations league": { name: "UEFA Nations League", country: "Europe" },
  "fifa world cup": { name: "World Cup", country: "International" },
  "world cup": { name: "World Cup", country: "International" },
  "uefa euro": { name: "European Championship", country: "Europe" },
  "euro": { name: "European Championship", country: "Europe" },
  "copa america": { name: "Copa America", country: "South America" },
  "afc asian cup": { name: "Asian Cup", country: "Asia" },
  "africa cup of nations": { name: "Africa Cup of Nations", country: "Africa" },
};

export function normalizeTeam(name: string): string {
  if (!name) return "";
  const cleaned = name
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\.$/, "")
    // strip common suffixes
    .replace(/\b(fc|cf|ac|sc|ssc|rc|as|cd|afc|vfl|vfb|tsg|rb|sk|fk|fk)\b/gi, "")
    .replace(/\s+/g, " ")
    .trim();
  const lower = cleaned.toLowerCase();
  if (TEAM_ALIASES[lower]) return TEAM_ALIASES[lower];
  // Title case the cleaned name
  return cleaned
    .split(" ")
    .map((w) => (w.length > 0 ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

export function normalizeLeague(name: string): { name: string; country: string } {
  if (!name) return { name: "Other", country: "International" };
  const lower = name.trim().toLowerCase();
  if (LEAGUE_ALIASES[lower]) return LEAGUE_ALIASES[lower];
  // Try contains-based match
  for (const key of Object.keys(LEAGUE_ALIASES)) {
    if (lower.includes(key) || key.includes(lower)) {
      return LEAGUE_ALIASES[key];
    }
  }
  return { name: name.trim(), country: "Unknown" };
}

export function makeExternalId(date: string, home: string, away: string): string {
  const h = home.toLowerCase().replace(/[^a-z0-9]/g, "");
  const a = away.toLowerCase().replace(/[^a-z0-9]/g, "");
  return `${date}:${h}:${a}`;
}
