/**
 * Synthetic Historical Seeder (for backtesting)
 * ─────────────────────────────────────────────────────────
 * Generates N months of synthetic-but-realistic settled matches + predictions
 * so the ML weight backtester (`scripts/backtest-weights.ts`) has data to
 * grid-search against.
 *
 * WHY THIS EXISTS:
 *   The backtester needs ~200+ settled predictions to produce stable weight
 *   estimates. The production DB has 0 settled matches right now (we haven't
 *   paper-traded yet). Rather than wait weeks for live data, we seed
 *   realistic synthetic history so the model can be validated NOW.
 *
 * REALISM:
 *   - Match outcomes are generated by a "true probability" that we then
 *     distort with per-source noise (calibrated sources get less noise).
 *   - Each prediction's `probability` is the engine's blended estimate.
 *   - Each prediction's `correct` flag is sampled stochastically based on
 *     the TRUE outcome, not the predicted probability — so model miss-
 *     calibration is realistic (some 0.80 picks will lose).
 *   - H2H data is synthesized for ~60% of matches (the rest have null H2H,
 *     like real life when ESPN doesn't have history for new fixtures).
 *   - Sources are pulled from the real Source table (uses their actual
 *     brier30d, clv30d, weight, calibrationA/B).
 *
 * USAGE:
 *   npx tsx scripts/seed-synthetic-history.ts [months] [matchesPerDay]
 *   # defaults to 3 months, 8 matches/day → ~720 matches, ~3000 predictions
 *
 *   Example: npx tsx scripts/seed-synthetic-history.ts 6 12
 *
 * NOTES:
 *   - This script DOES NOT TOUCH real matches. It only inserts rows with
 *     matchDate in the past and `externalId` prefixed with `synthetic-` so
 *     they're easy to identify and clean up.
 *   - Run `scripts/cleanup-synthetic-history.ts` to remove them.
 */

import { db } from "../src/lib/db";
import { loadSourceMLInfo } from "../src/lib/learning/parlay-ml";

// ──────────────────────────────────────────────────────────────────────────────
// Config
// ──────────────────────────────────────────────────────────────────────────────

const TEAM_POOL = [
  "Arsenal", "Chelsea", "Liverpool", "Man City", "Man United", "Tottenham",
  "Barcelona", "Real Madrid", "Atletico Madrid", "Sevilla",
  "Bayern Munich", "Dortmund", "Leipzig", "Leverkusen",
  "Juventus", "Inter", "Milan", "Napoli", "Roma",
  "PSG", "Marseille", "Lyon",
  "Ajax", "PSV", "Feyenoord",
  "Benfica", "Porto", "Sporting",
  "Celtic", "Rangers",
];

const LEAGUES = [
  { id: "eng.1", name: "Premier League" },
  { id: "esp.1", name: "La Liga" },
  { id: "ger.1", name: "Bundesliga" },
  { id: "ita.1", name: "Serie A" },
  { id: "fra.1", name: "Ligue 1" },
];

const MARKETS = [
  { market: "1x2", selections: ["1", "X", "2"] },
  { market: "ou25", selections: ["over", "under"] },
  { market: "btts", selections: ["yes", "no"] },
  { market: "double_chance", selections: ["1X", "X2", "12"] },
];

// ──────────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  const months = parseInt(process.argv[2] ?? "3", 10);
  const matchesPerDay = parseInt(process.argv[3] ?? "8", 10);

  console.log("═".repeat(78));
  console.log("  Synthetic Historical Seeder");
  console.log("═".repeat(78));
  console.log(`  Generating ${months} months × ~${matchesPerDay} matches/day`);
  console.log();

  // ── Load sources so we can attach realistic source probabilities ──────
  console.log("  [1/4] Loading source ML info...");
  const sourceMLMap = await loadSourceMLInfo();
  const sources = Array.from(sourceMLMap.values());
  if (sources.length === 0) {
    console.error("  ✗ No sources found in DB. Run `scripts/seed-sources.ts` first.");
    process.exit(1);
  }
  console.log(`        → ${sources.length} sources loaded`);
  console.log();

  // ── Load MarketLeagueClv rows (so predictions have realistic marketLeagueClv) ──
  // We'll just leave the existing CLV rows in place — the backtester queries
  // them directly. If none exist, the backtester will use 0.5 (neutral).

  // ── Generate matches ─────────────────────────────────────────────────
  console.log("  [2/4] Generating matches...");
  const today = new Date();
  const startDate = new Date(today);
  startDate.setMonth(startDate.getMonth() - months);

  let matchesCreated = 0;
  let predictionsCreated = 0;

  for (let d = new Date(startDate); d < today; d.setDate(d.getDate() + 1)) {
    // Skip ~20% of days (no fixtures that day, like weekdays in real life)
    if (Math.random() < 0.20) continue;

    const dateStr = d.toISOString().slice(0, 10);
    const matchesToday = Math.max(2, Math.round(matchesPerDay * (0.7 + Math.random() * 0.6)));

    for (let i = 0; i < matchesToday; i++) {
      const league = LEAGUES[Math.floor(Math.random() * LEAGUES.length)];
      const homeTeam = TEAM_POOL[Math.floor(Math.random() * TEAM_POOL.length)];
      let awayTeam = TEAM_POOL[Math.floor(Math.random() * TEAM_POOL.length)];
      while (awayTeam === homeTeam) {
        awayTeam = TEAM_POOL[Math.floor(Math.random() * TEAM_POOL.length)];
      }

      // ── Generate a "true" outcome for this match ──
      // Bias toward home win (real-life ~45% home, 27% draw, 28% away)
      const trueOutcomeRoll = Math.random();
      const trueOutcome: "home" | "draw" | "away" =
        trueOutcomeRoll < 0.45 ? "home" : trueOutcomeRoll < 0.72 ? "draw" : "away";

      // ── Generate a "true" goals total ──
      // Real-life avg ~2.6 goals/game. Sample from Poisson-ish.
      const trueGoals = Math.max(0, Math.round(poisson(2.6)));
      const homeScore = trueOutcome === "home"
        ? Math.ceil(trueGoals / 2) + (trueOutcome === "home" ? 1 : 0)
        : trueOutcome === "draw" ? Math.floor(trueGoals / 2)
        : Math.floor(trueGoals / 2);
      const awayScore = trueGoals - homeScore;

      // ── Build the match row ──
      const externalId = `synthetic-${dateStr}-${i}-${Math.random().toString(36).slice(2, 8)}`;
      const kickoffUtc = new Date(d);
      kickoffUtc.setHours(13 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 60), 0, 0);

      // ── Synthesize H2H for ~60% of matches ──
      const h2hJson = Math.random() < 0.6 ? generateH2HJson(homeTeam, awayTeam, trueOutcome) : null;

      // ── Synthesize odds JSON (used for bookOdds) ──
      const trueProbs = outcomeToProbabilities(trueOutcome);
      const oddsJson = JSON.stringify({
        home: 1 / Math.max(0.10, trueProbs.home + (Math.random() - 0.5) * 0.05),
        draw: 1 / Math.max(0.10, trueProbs.draw + (Math.random() - 0.5) * 0.05),
        away: 1 / Math.max(0.10, trueProbs.away + (Math.random() - 0.5) * 0.05),
        over25: 1 / Math.max(0.10, (trueGoals > 2 ? 0.60 : 0.40) + (Math.random() - 0.5) * 0.05),
        under25: 1 / Math.max(0.10, (trueGoals > 2 ? 0.40 : 0.60) + (Math.random() - 0.5) * 0.05),
      });

      // ── Insert the match ──
      const match = await db.match.create({
        data: {
          externalId,
          matchDate: dateStr,
          kickoffUtc,
          kickoffBrussels: kickoffUtc.toISOString(),
          // leagueId intentionally null — we don't want to fake a League row
          // association. The backtester treats null leagueId as "no
          // market-league CLV available" and uses the neutral 0.5 fallback.
          homeTeam,
          awayTeam,
          status: "finished",
          homeScore,
          awayScore,
          htHomeScore: Math.max(0, homeScore - Math.floor(Math.random() * 2)),
          htAwayScore: Math.max(0, awayScore - Math.floor(Math.random() * 2)),
          oddsJson,
          openingOddsJson: oddsJson,
          closingOddsJson: oddsJson,
          h2hJson,
          resultProcessed: true,
        },
      });

      matchesCreated++;

      // ── Generate predictions for this match (3-5 markets) ──
      const numMarkets = 3 + Math.floor(Math.random() * 3);
      const usedMarkets = new Set<string>();
      for (let m = 0; m < numMarkets; m++) {
        const marketDef = MARKETS[Math.floor(Math.random() * MARKETS.length)];
        if (usedMarkets.has(marketDef.market)) continue;
        usedMarkets.add(marketDef.market);

        const selection = marketDef.selections[Math.floor(Math.random() * marketDef.selections.length)];

        // ── Compute "true" probability for this selection ──
        const trueProb = computeTrueProb(marketDef.market, selection, trueOutcome, trueGoals);

        // ── Build per-source probabilities (with per-source noise) ──
        const consensusSources = Math.min(sources.length, 1 + Math.floor(Math.random() * 4));
        const sourcesForPred = sources.slice(0, consensusSources);
        const sourcesJson = JSON.stringify(
          sourcesForPred.map((s) => {
            // Better-calibrated sources (lower brier) get less noise
            const noise = (s.brier30d / 0.25) * 0.15 * (Math.random() - 0.5);
            const sourceProb = Math.max(0.05, Math.min(0.95, trueProb + noise));
            return { source: s.name, probability: sourceProb };
          })
        );

        // ── Engine probability = weighted blend of source probs ──
        const srcArr = JSON.parse(sourcesJson) as Array<{ source: string; probability: number }>;
        let weightedProb = 0;
        let weightSum = 0;
        for (const s of srcArr) {
          const srcInfo = sourceMLMap.get(s.source);
          const w = srcInfo?.weight ?? 0.5;
          weightedProb += w * s.probability;
          weightSum += w;
        }
        const engineProb = weightSum > 0
          ? Math.max(0.05, Math.min(0.95, weightedProb / weightSum))
          : trueProb;

        // ── Disagreement = stdev of source probs ──
        const probs = srcArr.map((s) => s.probability);
        const disagreement = probs.length > 1
          ? Math.sqrt(probs.reduce((s, p) => s + (p - engineProb) ** 2, 0) / probs.length)
          : 0;

        // ── Determine if the prediction was correct ──
        const correct = isCorrect(marketDef.market, selection, trueOutcome, trueGoals);

        // ── Book odds (slightly worse than fair, ~5% margin) ──
        const bookOdds = (1 / engineProb) * 0.95;

        // ── Create the prediction row ──
        await db.prediction.create({
          data: {
            matchId: match.id,
            market: marketDef.market,
            selection,
            confidence: Math.round(engineProb * 100),
            probability: engineProb,
            fairOdds: 1 / engineProb,
            bookOdds,
            edge: engineProb * bookOdds - 1,
            isTopPick: m === 0,
            isValueBet: engineProb * bookOdds - 1 > 0.05,
            consensusSources,
            disagreement,
            sourcesJson,
            evaluated: true,
            correct,
          },
        });
        predictionsCreated++;
      }
    }
  }

  console.log(`        → ${matchesCreated} matches, ${predictionsCreated} predictions created`);
  console.log();

  // ── Summary ──────────────────────────────────────────────────────────
  console.log("  " + "═".repeat(76));
  console.log("  DONE. Synthetic history seeded.");
  console.log("  " + "═".repeat(76));
  console.log(`  Date range: ${startDate.toISOString().slice(0, 10)} → ${today.toISOString().slice(0, 10)}`);
  console.log(`  Matches:    ${matchesCreated}`);
  console.log(`  Predictions: ${predictionsCreated}`);
  console.log();
  console.log("  Next steps:");
  console.log("    1. bun run scripts/backtest-weights.ts");
  console.log("    2. Review the top weight combos and update ML_WEIGHTS");
  console.log("    3. bun run scripts/cleanup-synthetic-history.ts  (to remove synthetic data)");
  console.log();

  await db.$disconnect();
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function poisson(lambda: number): number {
  // Knuth's algorithm
  const L = Math.exp(-lambda);
  let k = 0;
  let p = 1;
  do {
    k++;
    p *= Math.random();
  } while (p > L);
  return k - 1;
}

function outcomeToProbabilities(outcome: "home" | "draw" | "away"): { home: number; draw: number; away: number } {
  if (outcome === "home") return { home: 0.55, draw: 0.25, away: 0.20 };
  if (outcome === "draw") return { home: 0.30, draw: 0.40, away: 0.30 };
  return { home: 0.20, draw: 0.25, away: 0.55 };
}

function computeTrueProb(
  market: string,
  selection: string,
  trueOutcome: "home" | "draw" | "away",
  trueGoals: number
): number {
  if (market === "1x2") {
    if (selection === "1") return trueOutcome === "home" ? 0.55 : trueOutcome === "draw" ? 0.30 : 0.20;
    if (selection === "X") return trueOutcome === "draw" ? 0.40 : 0.27;
    if (selection === "2") return trueOutcome === "away" ? 0.55 : trueOutcome === "draw" ? 0.30 : 0.20;
  }
  if (market === "ou25") {
    const pOver = trueGoals > 2 ? 0.65 : 0.40;
    return selection === "over" ? pOver : 1 - pOver;
  }
  if (market === "btts") {
    const pYes = trueGoals >= 2 && Math.random() < 0.7 ? 0.65 : 0.40;
    return selection === "yes" ? pYes : 1 - pYes;
  }
  if (market === "double_chance") {
    if (selection === "1X") return trueOutcome === "home" || trueOutcome === "draw" ? 0.75 : 0.50;
    if (selection === "X2") return trueOutcome === "away" || trueOutcome === "draw" ? 0.75 : 0.50;
    if (selection === "12") return trueOutcome !== "draw" ? 0.80 : 0.55;
  }
  return 0.5;
}

function isCorrect(
  market: string,
  selection: string,
  trueOutcome: "home" | "draw" | "away",
  trueGoals: number
): boolean {
  if (market === "1x2") {
    if (selection === "1") return trueOutcome === "home";
    if (selection === "X") return trueOutcome === "draw";
    if (selection === "2") return trueOutcome === "away";
  }
  if (market === "ou25") {
    return selection === "over" ? trueGoals > 2 : trueGoals <= 2;
  }
  if (market === "btts") {
    // Approximate: BTTS yes if both teams scored at least 1
    // Since we synthesize, just use trueGoals >= 2 with 80% chance
    return selection === "yes" ? (trueGoals >= 2 && Math.random() < 0.85) : (trueGoals < 2 || Math.random() < 0.15);
  }
  if (market === "double_chance") {
    if (selection === "1X") return trueOutcome === "home" || trueOutcome === "draw";
    if (selection === "X2") return trueOutcome === "away" || trueOutcome === "draw";
    if (selection === "12") return trueOutcome !== "draw";
  }
  return false;
}

function generateH2HJson(
  homeTeam: string,
  awayTeam: string,
  trueOutcome: "home" | "draw" | "away"
): string {
  // Generate 5-10 past H2H meetings, biased toward the true outcome
  const numGames = 5 + Math.floor(Math.random() * 6);
  const matches: Array<{
    date: string;
    competitions: Array<{
      competitors: Array<{
        homeAway: "home" | "away";
        winner: boolean;
        score: string;
        team: { displayName: string };
      }>;
    }>;
  }> = [];

  for (let i = 0; i < numGames; i++) {
    const d = new Date();
    d.setMonth(d.getMonth() - (i + 1) * 6);
    const dateStr = d.toISOString().slice(0, 10);

    // 50% chance the outcome matches the true outcome (so H2H has signal)
    let outcome: "home" | "draw" | "away";
    const roll = Math.random();
    if (roll < 0.50) outcome = trueOutcome;
    else if (roll < 0.70) outcome = "draw";
    else outcome = Math.random() < 0.5 ? "home" : "away";

    const homeScore = outcome === "home" ? 2 : outcome === "draw" ? 1 : 0;
    const awayScore = outcome === "away" ? 2 : outcome === "draw" ? 1 : 0;

    matches.push({
      date: dateStr,
      competitions: [{
        competitors: [
          {
            homeAway: "home",
            winner: outcome === "home",
            score: String(homeScore),
            team: { displayName: homeTeam },
          },
          {
            homeAway: "away",
            winner: outcome === "away",
            score: String(awayScore),
            team: { displayName: awayTeam },
          },
        ],
      }],
    });
  }

  return JSON.stringify({
    matches,
    summary: {
      totalGames: numGames,
      homeWins: matches.filter((m) => m.competitions[0].competitors[0].winner).length,
      awayWins: matches.filter((m) => m.competitions[0].competitors[1].winner).length,
      draws: numGames - matches.filter((m) => m.competitions[0].competitors[0].winner || m.competitions[0].competitors[1].winner).length,
    },
  });
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
